language: cpp

env:
  global:
    - IS_COVERAGE_BUILD=0

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
      env:
        - COMPILER_CXX=g++-7
        - COMPILER_CC=gcc-7
        - IS_COVERAGE_BUILD=1

    - os: osx
      osx_image: xcode9.3
      compiler: gcc
      env:
        - COMPILER_CXX=g++
        - COMPILER_CC=gcc

    - os: osx
      osx_image: xcode9.3
      compiler: clang
      env:
        - COMPILER_CXX=clang++
        - COMPILER_CC=clang

sudo: required
dist: trusty

before_install:
  - chmod +x ci/*
  - source ci/travis-environment.sh
  - ci/travis-before-install.sh
  - ci/travis-system-info.sh

script:
  - ci/travis-script.sh

after_success:
  - ci/travis-after-success.sh

notifications:
  email: false
