version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version

build_script:
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -A %platform% ..
  - cmd: cmake --build . --config %configuration%

test_script:
  - cmd: ctest -C %configuration% -V --output-on-failure

only_commits:
  files:
    - deps/
    - examples/
    - include/
    - src/
    - test/
    - appveyor.yml
    - CMakeLists.txt
