version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version

build_script:
  - cmd: cmake -H. -Bbuild -A %PLATFORM%
  - cmd: cmake --build build --config %CONFIGURATION%

test_script:
  - ps: |
      cd build/test/unit/$($env:CONFIGURATION)
      ls
      .\CppAIKit-test.exe -s -r junit -o junit_test_results.xml
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\junit_test_results.xml))

only_commits:
  files:
    - deps/
    - examples/
    - include/
    - src/
    - test/
    - appveyor.yml
    - CMakeLists.txt
